### PR TITLE
Changes in InventoryManager and PlotManager, and implementation of State Class

### PR DESCRIPTION
**Pull request by angelaaajing**
-Add setters and getters for InventoryManager and PlotManager
-Add rent attribute to InventoryManager
-Add increaseRent and removeRent method to InventoryManager and add a call of increaseRent in PlotManager.createNewPlot.
-State Class implementation

### CODE REVIEW

**Review by DavidGorospe — APPROVED** [review]
- Good organization of save state use case in its own package
- Game state methods gather the correct information to save, load and initialize
- Use case interactor changes are necessary for save state use case

**Review by dianzrong — DISMISSED** [review]
There's no way to add plots. (Since it was removed from PlotManager and not added to InventoryManager)

**Review by dianzrong — APPROVED** [review]
Wow, you did so much! Looks good to me!! =)

**Review by sid19arya — APPROVED** [review]
Hey, it looks pretty good, so I am approving the changes  - i think it works but it would be a good idea to test, I do have some additional notes tho:
- We are not all familiar with how the io thing so could you just add some documentation and stuff, specifically when you are using the io package. 
- Additionally, your initialize game method only gives a name to the state class, we 
also need  to initialize an inventory with a set amount of money as well as plot(s)
depending on how we what we want the user to start off with. Initialize 
game should also make those calls?

Although I think you did a great job! :)

**Review by Jason0303132 — COMMENTED** [review]
Hey, the code looks good, and it seems to me that it will run properly given that we implement the rest of the project correctly.

However , it may be good to have documentation dictating which each part of the code does, so that when we start testing the code and an error occurs we can pinpoint which part of the code is at fault, as well as how we can fix the issue.

Overall, good work.

**Pull request merged**
