### PR TITLE
Leaderboard Screen

### PR DESCRIPTION
**Pull request by dianzrong**
Mostly implemented leaderboard screen (no back button yet) and made corresponding changes to leaderboard (i.e. removed the emojis from the string that holds the leaderboard).

- Note that displaying rankings in a human friendly way was moved from in the Share class to the Leaderboard class

### CODE REVIEW

**Review by jennnoh — DISMISSED** [review]
there is a merge conflict

**Review by jennnoh — APPROVED** [review]
looks amazing now!

**Review by angelaaajing — APPROVED** [review]
Looks good!!! :)

**Review by DavidGorospe — APPROVED** [review]
- UI for share screen is implemented correctly

**Pull request merged**
