### PR TITLE
Bugs fixed and changed

### PR DESCRIPTION
**Pull request by jennnoh**
- bugs are fixed and place, harvest, and extract methods are implemented without errors
- changed name attributes of yieldable products
- minor changes (deleted unused methods etc.)

### CODE REVIEW

**Review by dianzrong — DISMISSED** [review]
Good work finding the small differences !!!

**Review by DavidGorospe — DISMISSED** [review]
- Changes to yieldable names are necessary for null exception errors
- bug fixes for place method is correct
- extract/harvest are fixed

**Review by dianzrong — APPROVED** [review]
Good work finding the small differences !!!

**Review by DavidGorospe — APPROVED** [review]
- Changes to yieldable names are necessary for null exception errors
- bug fixes for place method is correct
- extract/harvest are fixed

**Review by Jason0303132 — APPROVED** [review]
Looks good, nice changes to fix the errors

**Pull request merged**
