### PR TITLE
Updated Shared Classes and Implemented More Entities

### PR DESCRIPTION
**Pull request by DavidGorospe**

### CODE REVIEW

**Review by dianzrong — DISMISSED** [review]
Looks good to me =)

**Comment by jennnoh** [comment]
looks good to me as well

**Review by angelaaajing — DISMISSED** [review]
Looks good!!

**Review by jennnoh — DISMISSED** [review]

**Review by jennnoh — APPROVED** [review]

**Review by angelaaajing — APPROVED** [review]
Looks good to me

**Review by sid19arya — APPROVED** [review]
Hey, this look great :)

**Review by dianzrong — APPROVED** [review]
Yay for hashmaps

**Pull request merged**
