### PR TITLE
Add tests for state class

### PR DESCRIPTION
**Pull request by angelaaajing**
-add test cases for State class
-add getter method for productStringDictionary in InventoryManager
-add setup for productStringDictionary in State class

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- Wide variety of test cases for Save State use case

**Review by DavidGorospe — DISMISSED** [review]
- Wide variety of test cases for Save State use case

**Review by DavidGorospe — APPROVED** [review]
- Correct updates to save state use case for String type inventory
- Wide variety of test cases for Save State use case

**Review by dianzrong — APPROVED** [review]
I like the new hashmap getter and how it aligns with clean architecture. Is there anyway we can write more tests to check the correctness of loading saved farms?

**Review by sid19arya — APPROVED** [review]
Nice job adding the prodString Dictionary setup to the game initialization, 
Great Test Cases - I see that you added another method in InvenManager for testing to help making sure everything is working correctly, this is a great idea.
I like that you are testing the Exception cases too
Great Job :)

**Pull request merged**
