### PR TITLE
Implement NextDay Use Case

### PR DESCRIPTION
**Pull request by angelaaajing**
-Implement NextDay and NextDayController Class; Write test cases for NextDay
-Implement ActionListener for NextDay and Farm button in the MenuScreen
-Delete controllers for EndGameConditions and RandomEvents since these two classes will be directly called by NextDay class
-In EndgameConditions, change the threshold of lose game from money less than 0 to less than the rent need to pay; also change string contents.
-Add getter for rent in InventoryManager; add setter for daysLeftToHarvest in Plot

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- End of game messages are implemented correctly
- Wide variety of tests for next day usecase
- Nextday use case implemented correctly

**Review by DavidGorospe — APPROVED** [review]
- End of game messages are implemented correctly
- Wide variety of tests for next day usecase
- Nextday use case implemented correctly

**Review by dianzrong — COMMENTED** [review]
I like the capitals in the printed strings. I also like the javadocs for the tests that keep track of what they do.

**Review by Jason0303132 — APPROVED** [review]
Looks good to to merge

**Review by dianzrong — COMMENTED** [review]
I like the documentation for the tests!

**Review by dianzrong — APPROVED** [review]

**Pull request merged**
