### PR TITLE
updated imports for my usecase, and Leaderboard *** ALSO added changes for testCases ***

### PR DESCRIPTION
**Pull request by Jason0303132**
deleted HellowWorld Test, added a Test for my usecase, changed Leaderboard too so that the import is updated

*** Changes added with Implementation of Test Cases ***

In Leaderboard I had to Comment out line 13-18 b/c there was an error in the code that prevented my from running tests. 

I made removeMoney and addMoney in InventoryManager static

I made myItems in Inventory get initalized

I changed checkWinSpeicies in EndgameConditions so that now its if you have greater than or equal to 2 species instead of just having 6 species to win

Added testcases for True/False for all the checkers with comments

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- Fixes to import statements and state calls are correct
- Package renaming of endgameconditions_feature fits package naming conventions
- Presenter is acting as the View, where it is directly outputting/displaying information to the user. Presenter is supposed to turn the output data from the usecase layer into readable data for the View to display. Under the circumstances of our recent Clean Architecture discussion, this is okay for now
- Test case doesn't accurately check the validity and correctness of checkWinMoney since there is no initialization to the money attribute for this test. Will approve though to prevent further workflow errors

**Review by DavidGorospe — DISMISSED** [review]
- Fixes to import statements and state calls are correct
- Package renaming of endgameconditions_feature fits package naming conventions
- Presenter is acting as the View, where it is directly outputting/displaying information to the user. Presenter is supposed to turn the output data from the usecase layer into readable data for the View to display. Under the circumstances of our recent Clean Architecture discussion, this is okay for now
- Proper initialization of inventory is good so that it's actually defined and not null
- Reset functions are implemented correctly as needed for test cases
- Test cases for win and lose conditions are implemented correctly

**Review by jennnoh — DISMISSED** [review]

**Review by dianzrong — APPROVED** [review]
I like how you changed the package's name to be all lowercase.
Additional notes:
- for checkWinSpecies, isn't there more than 2 species now?
- It may be better to have a @aftereach tag for your test so you don't have to say InventoryManager.reset() at the end of each of them

**Comment by Jason0303132** [comment]
> I like how you changed the package's name to be all lowercase. Additional notes:
> 
> * for checkWinSpecies, isn't there more than 2 species now?
> * It may be better to have a @aftereach tag for your test so you don't have to say InventoryManager.reset() at the end of each of them

**Comment by Jason0303132** [comment]
-for checkWinSpecies, isn't there more than 2 species now?
Yep, I just changed it to two species to make the test case easier to write, instead of having to initialize all 6 species before

-It may be better to have a @aftereach tag for your test so you don't have to say InventoryManager.reset() at the end of each of them
Yep, I was thinking the same thing, will implement in my next pull request

**Review by DavidGorospe — CHANGES_REQUESTED** [review]
- Fixes to import statements and state calls are correct
- Package renaming of endgameconditions_feature fits package naming conventions
- Presenter is acting as the View, where it is directly outputting/displaying information to the user. Presenter is supposed to turn the output data from the usecase layer into readable data for the View to display. Under the circumstances of our recent Clean Architecture discussion, this is okay for now
- Proper initialization of inventory is good so that it's actually defined and not null
- Reset functions are implemented correctly as needed for test cases
- Test cases for win and lose conditions are implemented correctly
Changes to be made:
- Fix the compiler error that's occurring in inventory manager. The getName() method is causing this. Look at main and see how we fixed it there and do the same for your file and re-commit.

**Pull request closed without merging**
