### PR TITLE
Implemented UseCaseBoundary interface and CheckProgress feature 1

### PR DESCRIPTION
**Pull request by DavidGorospe**
- Implemented UseCaseInteractorBoundary interface, which allows for input/output between usecase layer and interface adapter layer.
- Implemented CheckProgressBoundary which extends UseCaseInteractorBoundary interface, which allows for the CheckProgress feature to retrieve data from entities without violating dependency rule.
- Implemented CheckProgressController which will read a user's command input and call the boundary input method in CheckProgressBoundary.
- Implemented gameProgress() method in State class which interacts with the entity layer to fetch user's inventory, plots and money information.
- Implemented CheckProgressPresenter which converts user's inventory, plot and money information into strings to form the viewmodel to be displayed.
- Implemented CheckProgressView which prints and displays the user's inventory, plot and money information

### CODE REVIEW

**Review by angelaaajing — CHANGES_REQUESTED** [review]
What a great contribution for adding controller, presenter, view and input/output boundary! Also, good documentation!
However, I still have some suggestions:
1. CheckProgressBoundary class implements both Input Boundary and Output Boundary Interfaces, but Output Boundary directly uses Presenter, which seems to violate the dependency theory.  So maybe we can split interface UseCaseInteractorBoundary into two interfaces, and use the presenter to implement the output boundary.
2.  State.gameProgess() can be separated from the State class since it belongs to the Check Progress use case, which can be the model of it. Then in this case, your controller can directly call your use case, which does not need an input boundary any more i think.

**Review by dianzrong — DISMISSED** [review]
I agree with everything Jing said! 
A couple things I wanted to add:
- I like how you made your code explicit in terms of clean architecture
- there's a typo in line 11 CheckProgressPresenter (viewmoddel not "viemodel")

**Review by angelaaajing — DISMISSED** [review]

**Review by jennnoh — APPROVED** [review]

**Review by dianzrong — COMMENTED** [review]
Most of your additional changes look good. 
But note: I thought the name of the farm was in Inventory Manager (so may need to change some lines in State and in Leaderboard)

**Review by Jason0303132 — APPROVED** [review]
Good job, implementing Controller/Presenter/View, and good implementation of Clean Architecture. Also, good documentation of portions of your code to show what each part of the code.

**Review by dianzrong — APPROVED** [review]
I think it would be better for you to move lines 24-26 into the setup method. I like how you have only 1 assertions statement.

**Pull request closed without merging**
