### PR TITLE
Added FarmScreen

### PR DESCRIPTION
**Pull request by jennnoh**
Added FarmScreen which has three functions: place, harvest and extract

### CODE REVIEW

**Comment by jennnoh** [comment]
- removed the white space: ' chicken' -> 'chicken'
- added farm screen which has three buttons: place harvest and extract

**Review by DavidGorospe — APPROVED** [review]
- fixes to test cases are good as they accommodate to the new names for the methods in Farmer
- UI for farmer usecase is correctly implemented

**Review by angelaaajing — APPROVED** [review]
-Implement FarmScreen properly
-Errors fixed for Farmer
-Make methods in PlotManager be static

**Review by dianzrong — APPROVED** [review]
I noticed some of the lines seem to be code that's just commented out. I think we should change those in the future.

Other than that, looks good to me!

**Pull request merged**
