### PR TITLE
9 feature 6 interacting with the market

### PR DESCRIPTION
**Pull request by sid19arya**
Shopper Use Case Essentials Implimented:
- adder shopper use case package and shopper class
- created and implimented shopper use case methods.

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- value attribute implemented correctly for plots
- Good organization of putting InteractWithMarket use case in its own package
- Shopper methods implemented correctly
- Checking instances of products implemented correctly

**Review by dianzrong — CHANGES_REQUESTED** [review]
In sell_to_market, you make 2 calls to **InventoryManager.removeItem(item, quantity)**, one in check_valid_sale(...) and one explicitly in line 23. 

However, in the implementation of InventoryManager.removeItem, the item is removed (if possible). So in sell_to_market, the item is removed twice (if possible). 

So maybe we would need to implement a separate method in InventoryManager that ONLY checks if it's possible to remove the item. Or we can just remove the call to removeItem in line 23?

Also instead of using PlotManager.addplot, may need to change this to PlotManager.createnewplot() because that's what Jing implemented

**Review by dianzrong — DISMISSED** [review]
Nice changes! 🏅

**Review by DavidGorospe — DISMISSED** [review]
- Implementation of retrieving the value of a plot is correct, but may need to change the value later on for quality of life improvements
- Typo with package "InterctWithMarketUseCase". I assume its supposed to be "InteractWithMarketUseCase"
- Shopper file abides by the dependency rule by only referencing Yieldables in the entities layer and InventoryManager and PlotManager in the use case layer (doesn't call anything in the interface adapter layer)
- In the sell_to_market method, the check to see if an item is a valid, sellable item is a good way to prevent error. Maybe add a message saying that this item is not sellable to the market in the future
- Lines 19, 21, and 23 in Shopper correctly updates the user's money and inventory
- Same suggestions and comments from sell_to_market method apply to buy_from_market method and buy_plot method
- ShopperController makes correct calls to Shopper to execute the feature's purpose and returns whether the call was successful or not. As a temporary way of saying the function call was successful, the boolean return is fine, but in the future, maybe a message should be displayed to the user.
- Try to add comments and java documentations to all your classes and functions
-

**Review by angelaaajing — DISMISSED** [review]

**Review by DavidGorospe — APPROVED** [review]
- Implementation of retrieving the value of a plot is correct, but may need to change the value later on for quality of life improvements
- Typo with package "InterctWithMarketUseCase". I assume its supposed to be "InteractWithMarketUseCase"
- Shopper file abides by the dependency rule by only referencing Yieldables in the entities layer and InventoryManager and PlotManager in the use case layer (doesn't call anything in the interface adapter layer)
- In the sell_to_market method, the check to see if an item is a valid, sellable item is a good way to prevent error. Maybe add a message saying that this item is not sellable to the market in the future
- Lines 19, 21, and 23 in Shopper correctly updates the user's money and inventory
- Same suggestions and comments from sell_to_market method apply to buy_from_market method and buy_plot method
- ShopperController makes correct calls to Shopper to execute the feature's purpose and returns whether the call was successful or not. As a temporary way of saying the function call was successful, the boolean return is fine, but in the future, maybe a message should be displayed to the user.
- Try to add comments and java documentations to all your classes and functions

**Review by angelaaajing — APPROVED** [review]
looks good to me :D

**Review by dianzrong — APPROVED** [review]
👍

**Pull request merged**
