### PR TITLE
Raise Crops and Animals use case: new branch

### LINKED ISSUE #47: [Feature 5] Raising Crops and Animals (Part 2)
Allows user to raise crops and animals. Includes placeAnimals and placeCrops in Farmer class & havest and place method in PlotManager class.

### PR DESCRIPTION
**Pull request by jennnoh**
- Added Raising Crops and Animals use cases: Farmer and FarmerController
- For the Farmer class, added two methods place_animals and place_crops: Let the player choose which plot to place his/her animal or crop and get a plotId.
- For Plot Manager, added harvest, extract, and place methods. Harvest method harvests crops and empties the plot & extract method extracts yields from a plot but does not empty the plot (since animals are still there)
- Place method places products to a plot
- Added getter for getProduct

### CODE REVIEW

**Review by angelaaajing — DISMISSED** [review]
Great implementation of Farmer class and add a controller to it!! :)

**Comment by jennnoh** [comment]
deleted .idea and .gradle files!

**Review by DavidGorospe — DISMISSED** [review]
- Please add java docs for future reference
- setter for emptyPlots is implemented correctly
- harvest and extract correctly updates inventory and plots
- plots updated correctly when placing products

**Review by DavidGorospe — APPROVED** [review]
- Please add java docs for future reference
- setter for emptyPlots is implemented correctly
- harvest and extract correctly updates inventory and plots
- plots updated correctly when placing products

**Review by angelaaajing — APPROVED** [review]
-Great implementation of Farmer class and add a controller to it!! :)
-Documentation still needed.

**Review by Jason0303132 — APPROVED** [review]
Looks good, I think it works properly. Except your violate clean architecture by printing and taking in inputs, but we can fix that later on.

**Pull request merged**
