### PR TITLE
Implemented Share and Leaderboard Screens

### PR DESCRIPTION
**Pull request by dianzrong**
As the title states, I implemented Share and Leaderboard Screens. This means they work, they are connected to and from the Menu Screen.

To implement with swing, I had to change some of the Share and Leaderboard returns and then changed the corresponding tests. 

Additionally, for the emojis, I uploaded images.

Also added Javadocs.

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- UI for share usecase implemented correctly
- UI for leaderboard usecase implemented correctly

**Review by Jason0303132 — APPROVED** [review]
Looks good, I think these should work properly

**Review by sid19arya — APPROVED** [review]
Good implementation of the two pages, I like the way in which the plots are shown as images I think it s acool idea. Also a lot of bug fixes which makes the code a lot more smooth. Nice Job

**Review by DavidGorospe — APPROVED** [review]
- UI for share usecase implemented correctly
- UI for leaderboard usecase implemented correctly

**Pull request merged**
