### PR TITLE
Final changes

### PR DESCRIPTION
**Pull request by dianzrong**
Hopefully final changes.
- bug fixes
- fixing package naming conventions
- Jing's edits to save states to put them in a collective folder and track leaderboard

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- Deletion of unnecessary commented code is good
- Warnings have been fixed
- Renaming of packages fits naming scheme

**Review by angelaaajing — APPROVED** [review]
I like how you organized classes and packages! Great contribution to fix all errors and warnings. More test cases were added to test some controllers. Good job!! : )

**Review by jennnoh — APPROVED** [review]
Thank you for refactoring the packages, and fixing warnings and bugs! The files look so much neater🙂 (+ Jing for save states!)

**Review by DavidGorospe — APPROVED** [review]

**Review by DavidGorospe — APPROVED** [review]
- Deletion of unnecessary commented code is good
- Warnings have been fixed
- Renaming of packages fits naming scheme

**Pull request merged**
