### PR TITLE
Share: javadocs, tests, refactoring

### PR DESCRIPTION
**Pull request by dianzrong**
- added javadocs
- refactored Sharer.getRanking and getFarmAppearance
  - if I have more time I'll refactor getFarmAppearance so new entities can be added more easily
- added tests

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- Potato and Tomato extend Crop class as they should, and their constructor correctly initializes attributes
- Java documentation clearly explains functionality of classes and methods
- Good that you eliminated State call from your use case for separation
- Leaderboard Controller correctly calls leaderboard usecase
- ShareController correctly calls share usecase
- Excited to see the functionality of the emojis
- Test cases are abundant and cover various cases

**Review by jennnoh — DISMISSED** [review]
- javadocs are added and easy to understand what each method does
- incorporated tests that cover common use cases
- refactored sharer.getRanking and getFarmAppearance follow clean architecture

**Review by DavidGorospe — DISMISSED** [review]
- Potato and Tomato extend Crop class as they should, and their constructor correctly initializes attributes
- Java documentation clearly explains functionality of classes and methods
Good that you eliminated State call from your use case for separation
- Leaderboard Controller correctly calls leaderboard usecase
- ShareController correctly calls share usecase
- Excited to see the functionality of the emojis
- Test cases are abundant and cover various cases
- Change to type annotations make no errors

**Review by sid19arya — DISMISSED** [review]
Great Changes!
Testing is extensive and detailed - the large amount of changes can be incorporated with confidence since we know they work.
The essential javadocs as well as additional code comments to explain complicated logic is present!
The code for Leaderboard and Sharer looks a lot cleaner and efficient while still functioning as needed.

**Review by angelaaajing — CHANGES_REQUESTED** [review]
Great documentation and testing! 
But StateStateUseCase package needed to be deleted it before merging.

**Review by angelaaajing — APPROVED** [review]
Looks good to me : )

**Review by jennnoh — APPROVED** [review]
- javadocs look great and stateusecase package was deleted before merging
- tests cover various use cases

**Review by DavidGorospe — APPROVED** [review]
- Potato and Tomato extend Crop class as they should, and their constructor correctly initializes attributes
- Java documentation clearly explains functionality of classes and methods
- Good that you eliminated State call from your use case for separation
- Leaderboard Controller correctly calls leaderboard usecase
- ShareController correctly calls share usecase
- Excited to see the functionality of the emojis
- Test cases are abundant and cover various cases
- Change to type annotations make no errors

**Pull request merged**
