### PR TITLE
Implemented parts of GUI using Swing in folder (UI) in file GameUI

### PR DESCRIPTION
**Pull request by Jason0303132**
Made Title screen ->Take Name Screen -> Save or Load Screen

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- This is the backend of the UI so can't really tell what the visual is of the UI but from what you have, I believe you have the login screen, which looks like it is implemented properly

**Review by DavidGorospe — DISMISSED** [review]
- This is the backend of the UI so can't really tell what the visual is of the UI but from what you have, I believe you have the login screen, which looks like it is implemented properly
- Login screen branches off to the other use case screens

**Review by sid19arya — DISMISSED** [review]
I think this is a great foundation for the UI.
- A very good idea to lay out all the different screens: Helps Stay in line with solid design principles
- I thinking pushing a basic class for all the different screens begin with is smart as you can always build on top of them and it allows everyone to observe and contribute wherever they can
- As I imagine we would have  basic layout in all screens (panel, frames, buttons etc,). Maybe you can consider a factory design pattern to do this basic implementation for all screens. 
-- Or any other strategy to help work around having repeated code
Overall, I think this is a great contribution

**Review by DavidGorospe — APPROVED** [review]
- This is the backend of the UI so can't really tell what the visual is of the UI but from what you have, I believe you have the login screen, which looks like it is implemented properly
- Login screen branches off to the other use case screens

**Review by jennnoh — APPROVED** [review]
- The UI works and the title and name screen are implemented

**Review by angelaaajing — APPROVED** [review]
Good idea to create different screens for UI ! The codes looks implemented properly.

**Pull request merged**
