### PR TITLE
EndGameConditions Part 2 

### LINKED ISSUE #42: [Feature 3] Winning/Losing conditions (Part 2)
Includes static methods, checkWinMoney, checkWinSpecies, checkLose and endGame, as well as test cases for checkWinMoney, checkWinSpecies, checkLose

### PR DESCRIPTION
**Pull request by Jason0303132**
This is a new Branch for EndGameConditions, due to errors on Github on the old branch

Everything that was on the old EndGameConditions Branch is implemented in additon to:

Implemented: EndgameConditions, endgameConditionsTest

In InventoryManager initiatizliaed myInventory

### CODE REVIEW

**Review by DavidGorospe — DISMISSED** [review]
- Warning checks have been resolved in EndgameConditions
- Reset method implemented correctly for testing purposes
- Tests cover a wide variety of cases for Endgame Conditions use case

**Review by dianzrong — DISMISSED** [review]
- I like how you simplified a lot of the code in EndGameConditions, making it less bloated (and less smelly haha)
- maybe it would be better to change 2 assertion statements to an assertion statement with expected and actual
- you can also add edge casses (ex. an inventory size of 2 and money of 1500)

**Review by DavidGorospe — DISMISSED** [review]
- Warning checks have been resolved in EndgameConditions
- Reset method implemented correctly for testing purposes
- Tests cover a wide variety of cases for Endgame Conditions use case

**Review by sid19arya — DISMISSED** [review]
A lot of this is cleanup of the code: I think it is great that you are doing this and I think everyone else should be doing the same.
Great job adding test cases too - Although you should also consider adding a test case for the controller too. Ofcourse this is trivial and there is no reason why the controller shouldn't work, but its always better to test every method you have implemented
Great Contribution.

**Review by jennnoh — DISMISSED** [review]
There is a merge conflict that should be resolved

**Review by jennnoh — DISMISSED** [review]
autograding failed :/

**Review by DavidGorospe — APPROVED** [review]
- Warning checks have been resolved in EndgameConditions
- Reset method implemented correctly for testing purposes
- Tests cover a wide variety of cases for Endgame Conditions use case

**Comment by jennnoh** [comment]
- EndgameConditions an endgameConditionsTest are implemented correctly
- The merge conflict is fixed
- All checks have passed

**Review by jennnoh — APPROVED** [review]
- EndgameConditions an endgameConditionsTest are implemented correctly
- The merge conflict is fixed
- All checks have passed

**Review by angelaaajing — APPROVED** [review]
EndGameConditions implemented properly and great documentation for different test cases!

**Pull request merged**
