### PR TITLE
Edited checkprogress files with minor fixes and tests

### PR DESCRIPTION
**Pull request by DavidGorospe**
- Created a separate java class for CheckProgress use case that contains the gameProgress() method
- Fixed warning errors in the files involving the CheckProgress usecase
- Implemented a test case for CheckProgress use case and explained cases that aren't/can't be tested

### CODE REVIEW

**Review by dianzrong — DISMISSED** [review]
I like how you mentioned what wasn't tested and why. That being said, please add javadocs with parameters and return descriptors to make the code easier to understand.

**Review by angelaaajing — APPROVED** [review]
-Wide variety of test case for checkprogress
-Useful documentation in test to show why some cases cannot be tested

**Review by dianzrong — APPROVED** [review]
I like the small changes and especially how you mention what tests aren't done and why. That being said I think you could add a test for CheckProgressController

**Review by Jason0303132 — APPROVED** [review]
Overall, good changes, nice job catching the errors in CheckProgressPresenter.  Good addition of JavaDoc

**Pull request merged**
