### PR TITLE
Edited and Implemented Elements of Checkprogress

### PR DESCRIPTION
**Pull request by DavidGorospe**
- Added a new test case for testing the string that contains the user's information in a certain format
- Edited the backend of the CheckProgress usecase so that CheckProgressController just calls CheckProgress, where all the usecase work occurs
- Implemented the UI for CheckProgress

### CODE REVIEW

**Review by Jason0303132 — APPROVED** [review]
Everything looks good, good job on implementing the UI, although I think we can add Jpanels.

**Review by angelaaajing — APPROVED** [review]
Looks good :)

**Review by dianzrong — APPROVED** [review]
I like the changes you made to CheckProgressController so it follows clean architecture more easily. Good work on the UI! I like the new tests !!

**Review by jennnoh — APPROVED** [review]
- test cases for the string are implemented correctly
- the UI for CheckProgress works

**Pull request merged**
