### PR TITLE
Update on State class and its controller

### PR DESCRIPTION
**Pull request by angelaaajing**
1. Solve bugs in State class. Make Inventory, Plot, Product implement Serializable.
2. Implement State Controller
3. Remove name attribute in State to Inventory. Add setters and getters to both Inventory and InventoryManager.
4. Remove rent attribute in InventoryManager to Inventory. Add increaseRent and removeRent method to both Inventory and InventoryManager.

### CODE REVIEW

**Comment by jennnoh** [comment]
- Bugs seem to be fixed and product, plot and make inventory changed to be serializable correctly
- the package save_state_use_case was renamed following package naming conventions
- Setters and getters of Inventory and InventoryManger are implemented without issues 
- IncreaseRent and removeRent method were correctly added to both Inventory and InventoryManager.

**Review by jennnoh — COMMENTED** [review]
- Bugs seem to be fixed and product, plot and make inventory changed to be serializable correctly
- package save_state_use_case was renamed following package naming conventions
- Setters and getters of Inventory and InventoryManger are implemented without issues
- IncreaseRent and removeRent method were correctly added to both Inventory and InventoryManager.

**Review by jennnoh — APPROVED** [review]

**Review by dianzrong — APPROVED** [review]
Looks good to me although I thought we mentioned putting the farm name in Inventory Manager. Is it necessary to have it in Inventory as well ? Regardless, good work!

**Review by sid19arya — APPROVED** [review]
This looks great!
- All the bugs discussed were cleared up
- The code looks coherent and straightforward as well as adheres to clean architecture
- covering exceptions is also a great idea, especially when dealing with loading and initializing that game since that's where it is the most crucial to avoid errors.
Good job!

**Pull request merged**
