### PR TITLE
9 feature 6 interacting with the market

### PR DESCRIPTION
**Pull request by sid19arya**
- Added Shop Screen and all internal implementation.
- Integrated Shop Screen with MainScreen
- Added a Factory for creating JComponents

### CODE REVIEW

**Review by Jason0303132 — DISMISSED** [review]
Looks good

**Review by jennnoh — DISMISSED** [review]
Shopscreen is implemented and it looks great!

**Review by DavidGorospe — APPROVED** [review]
- UI for Shopper usecase is implemented correctly

**Review by Jason0303132 — APPROVED** [review]
Looks good

**Review by dianzrong — APPROVED** [review]
I like the factory!!! I also liked how u separated the different classes!

**Pull request merged**
